server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  security:
    user:
      name: test@naver.com
      password: 1q2w3e4r!

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.ckcprgdnytpw.ap-northeast-2.rds.amazonaws.com:3306/stussy-20220930
    username: admin
    password: 1qw3242e

mybatis:
  mapper-locations:
    - /mappers/*.xml


file:
  path: C:/seoyeong/kb1/springboot/stussy-clone-20220930-seoyeong/src/main/resources/static/upload/